import { useState } from 'react';
import { Code2, Copy, Palette, Send, ShieldCheck, Type, Upload } from 'lucide-react';
import type { ResumeData, SelectionMeta } from '../types';
export function Inspector({ resume, selection, onContent, onStyle, onCode, onPhoto }: { resume:ResumeData;selection:SelectionMeta;onContent:(value:string)=>void;onStyle:(key:string,value:string|number|boolean)=>void;onCode:()=>void;onPhoto:(file:File)=>void }){
  const [tab,setTab]=useState<'properties'|'code'>('properties');const [draft,setDraft]=useState(selection.content);
  const canEdit=!['page','avatar','section-title'].includes(selection.kind);
  return <aside className="insight-column"><div className="insight-heading"><div><span className="panel-kicker">INSPECT</span><h2>选择器</h2></div></div><div className="inspector-card"><div className="inspector-tabs"><button className={tab==='properties'?'active':''} onClick={()=>setTab('properties')}>属性</button><button className={tab==='code'?'active':''} onClick={()=>setTab('code')}><Code2 size={14}/>代码</button></div><div className="inspector-target"><div><strong>{selection.label}</strong><small>{selection.id}</small></div></div>
  {tab==='properties'?<>{canEdit&&<div className="inspector-section"><div className="inspector-label"><Type size={14}/>内容</div><textarea aria-label="选中区块的内容" className="inspector-textarea" value={draft} onChange={e=>setDraft(e.target.value)} rows={5} maxLength={6000}/><button className="code-sync-button" disabled={draft===selection.content} onClick={()=>onContent(draft)}>保存内容</button></div>}
  <div className="inspector-section"><div className="inspector-label"><Palette size={14}/>颜色</div><div className="color-row">{['#D96945','#193B35','#65735A','#315A64'].map(color=><button aria-label={`选择颜色 ${color}`} key={color} className="color-swatch" style={{background:color}} onClick={()=>onStyle('color',color)}/>)}<input aria-label="自定义颜色" type="color" value={selection.style.color} onChange={e=>onStyle('color',e.target.value)}/></div></div>
  <div className="inspector-section"><div className="inspector-label">字号 <span>{selection.style.fontSize}px</span></div><input aria-label="选中元素字号" className="range-input" type="range" min="8" max="48" value={selection.style.fontSize} onChange={e=>onStyle('fontSize',Number(e.target.value))}/></div><div className="inspector-section"><div className="inspector-label">下方间距 <span>{selection.style.marginBottom}px</span></div><input aria-label="选中元素间距" className="range-input" type="range" min="0" max="40" value={selection.style.marginBottom} onChange={e=>onStyle('marginBottom',Number(e.target.value))}/></div><div className="inspector-section inspector-toggle-row"><span>左侧强调线</span><button className={`toggle ${selection.style.accent?'on':''}`} aria-label="切换强调线" aria-pressed={selection.style.accent} onClick={()=>onStyle('accent',!selection.style.accent)}><span/></button></div>
  {selection.kind==='avatar'&&<div className="inspector-section"><div className="segmented-control">{(['circle','square'] as const).map(shape=><button className={resume.design.avatarShape===shape?'active':''} key={shape} onClick={()=>onStyle('avatarShape',shape)}>{shape==='circle'?'圆形':'方形'}</button>)}</div><label className="upload-avatar-button"><Upload size={14}/>上传头像<input aria-label="更换头像" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)onPhoto(f);e.target.value='';}}/></label></div>}</>:<div className="code-panel"><div className="code-panel-head"><span>当前组件安全样式</span><button aria-label="复制代码" className="quiet-icon" onClick={()=>void navigator.clipboard?.writeText(selection.code)}><Copy size={14}/></button></div><pre><code>{selection.code}</code></pre><div className="code-safe"><ShieldCheck size={13}/>AI不能执行任意HTML/JavaScript</div><button className="code-sync-button" onClick={onCode}><Send size={13}/>将代码同步到聊天框</button></div>}</div></aside>;
}
