import { Check, ChevronRight, Settings2, ShieldCheck, X } from 'lucide-react';
import type { ModelConfig, ModelPreset } from '../types';
export function ModelSettings({ config, presets, onChange, onClose, onSave }: { config: ModelConfig; presets: ModelPreset[]; onChange: (config: ModelConfig) => void; onClose: () => void; onSave: () => void }) {
  const selectedPreset = presets.find((preset) => preset.id === config.presetId);
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="model-modal" role="dialog" aria-modal="true" aria-labelledby="model-settings-title">
    <div className="modal-head"><div><span className="panel-kicker">MODEL GATEWAY / 03</span><h2 id="model-settings-title">AI 模型设置</h2><p>选择后端预设，或输入一个 OpenAI-compatible 的完整调用地址。</p></div><button className="quiet-icon" onClick={onClose} aria-label="关闭模型设置"><X size={17} /></button></div>
    <div className="model-mode-tabs"><button className={config.mode === 'preset' ? 'active' : ''} onClick={() => onChange({ ...config, mode: 'preset' })}><ShieldCheck size={15} /> 后端预设</button><button className={config.mode === 'custom' ? 'active' : ''} onClick={() => onChange({ ...config, mode: 'custom' })}><Settings2 size={15} /> 自定义模型</button></div>
    {config.mode === 'preset' ? <div className="preset-list">{presets.filter((preset) => preset.id !== 'custom').map((preset) => <button className={`preset-item ${config.presetId === preset.id ? 'active' : ''}`} key={preset.id} onClick={() => onChange({ ...config, presetId: preset.id, model: preset.model, url: preset.baseUrl })}><span className="preset-radio" /> <span><strong>{preset.label}</strong><small>{preset.provider} · {preset.model || '由后端环境变量决定'}</small><em>{preset.description}</em></span><ChevronRight size={15} /></button>)}</div> : <div className="model-form"><label>完整 URL<span>例如 https://api.openai.com/v1/chat/completions</span><input value={config.url} onChange={(event) => onChange({ ...config, url: event.target.value })} placeholder="https://.../v1/chat/completions" /></label><label>模型名称<input value={config.model} onChange={(event) => onChange({ ...config, model: event.target.value })} placeholder="gpt-4o-mini / deepseek-chat / qwen..." /></label><label>API Key <span>只存在当前浏览器会话，不会写入本地简历</span><input type="password" value={config.apiKey} onChange={(event) => onChange({ ...config, apiKey: event.target.value })} placeholder="sk-..." /></label><div className="model-note"><ShieldCheck size={14} /><span>前端会把自定义配置临时发给 Railway 后端代理，浏览器不会直接暴露跨域请求。</span></div></div>}
    {config.mode === 'preset' && selectedPreset && <div className="selected-preset"><span className="status-dot" /><div><strong>{selectedPreset.label}</strong><small>{selectedPreset.baseUrl} · {selectedPreset.model || '后端配置模型'}</small></div><span className="selected-label">READY</span></div>}
    <div className="modal-foot"><button className="ghost-button" onClick={onClose}>取消</button><button className="apply-button" onClick={onSave}><Check size={14} /> 保存模型选择</button></div>
  </section></div>;
}
