import { ChevronRight, History, Target } from 'lucide-react';
import type { ResumeVersion, EditOperation } from '../types';
const labels={matched:'有材料依据',partial:'部分匹配',missing:'待补充'};
export function MatchPage({version,onBack}:{version:ResumeVersion;onBack:()=>void}){
  const report=version.report; const total=report?.requirements.length??0; const matched=report?.requirements.filter(r=>r.status==='matched').length??0;
  return <div className="subpage match-page"><div className="subpage-head"><div><span className="panel-kicker">ROLE FIT</span><h1>岗位匹配</h1><p>{version.title} · {version.isDemo?'示例分析':'来自当前版本生成时的岗位分析'}</p></div><button className="outline-button" onClick={onBack}><ChevronRight size={14} className="rotate-back"/>返回编辑</button></div><div className="match-overview"><Target size={32}/><div className="match-overview-copy"><span className="match-badge">{matched} / {total} 项要求有明确依据</span><h2>{version.role}</h2><p>{report?.summary??'此旧版没有真实岗位分析，请从首页重新生成。'}</p><small>这不是录用概率或独立评估。编辑文案后不会自动更新，建议核对原始材料。</small></div></div><div className="requirements-list">{report?.requirements.map((item,i)=><article className={`analysis-card requirement-${item.status}`} key={i}><div className="requirement-head"><h3>{item.requirement}</h3><span>{labels[item.status]}</span></div><p><b>依据：</b>{item.evidence||'目前材料没有相应证据。'}</p>{item.suggestion&&<p><b>建议：</b>{item.suggestion}</p>}</article>)}</div>{version.warnings.length>0&&<div className="analysis-card"><h3>需要确认的信息</h3><ul>{version.warnings.map((text,i)=><li key={i}>{text}</li>)}</ul></div>}</div>;
}
export function HistoryPage({version,onBack,onRestore}:{version:ResumeVersion;onBack:()=>void;onRestore:(op:EditOperation)=>void}){
  return <div className="subpage history-page"><div className="subpage-head"><div><span className="panel-kicker">REVISION LOG</span><h1>修改历史</h1><p>只显示 {version.title} 的记录，恢复不会影响其他版本。</p></div><button className="outline-button" onClick={onBack}>返回编辑</button></div><div className="history-summary"><div><strong>{version.past.length}</strong><span>可撤销修改</span></div><div><strong>{version.history.length}</strong><span>历史记录（保留最近40条）</span></div><div><strong>{version.messages.length}</strong><span>编辑对话</span></div></div>
  {version.history.length===0?<div className="empty-history"><History size={28}/><h2>还没有修改记录</h2><p>在工作台保存内容或应用AI修改后，这里会记录修改前后状态。</p><button className="outline-button" onClick={onBack}>开始编辑</button></div>:<div className="history-list">{version.history.slice().reverse().map((op,i)=><article className="history-item" key={op.id}><span className="history-index">{String(i+1).padStart(2,'0')}</span><div><strong>{op.label}</strong><small>{new Date(op.createdAt).toLocaleString('zh-CN')} · {op.source==='ai'?'AI修改':op.source==='restore'?'恢复操作':'手动编辑'}</small><details><summary>查看修改前后</summary><div className="history-diff"><pre>{JSON.stringify(op.before,null,2)}</pre><pre>{JSON.stringify(op.after,null,2)}</pre></div></details><button className="outline-button" onClick={()=>onRestore(op)}>恢复到此修改之后</button></div></article>)}</div>}
  {version.messages.length>0&&<section className="history-conversations"><h2>编辑对话</h2>{version.messages.map(m=><div className="history-item" key={m.id}><span>{m.role==='user'?'你':'AI'}</span><p>{m.content}</p></div>)}</section>}</div>;
}
