import type { z } from 'zod';
import type { resumeSchema, nodeStyleSchema, reportSchema, generationSchema, materialSchema } from '../shared/contracts';
import type { ReasoningEffort } from '../shared/modelProtocol';
export type ResumeData = z.infer<typeof resumeSchema>;
export type NodeStyle = z.infer<typeof nodeStyleSchema>;
export type Project = ResumeData['projects'][number];
export type NodeKind = 'page' | 'name' | 'role' | 'contact' | 'avatar' | 'summary' | 'section-title' | 'project-title' | 'project-description' | 'experience' | 'education' | 'skills' | 'awards' | 'custom-title' | 'custom-content' | 'text';
export type SelectionMeta = { id: string; label: string; breadcrumb: string; kind: NodeKind; path: string; content: string; style: Required<NodeStyle>; code: string; design?: ResumeData['design'] };
export type EditPatch = { id: string; targetNodeId: string; operation: 'setStyle' | 'rewriteText' | 'setTheme'; path: string; value: string | number | boolean; reason: string; requiresConfirmation: boolean; preview: string };
export type ChatMessage = { id: string; role: 'assistant' | 'user'; content: string; meta?: string };
export type MatchReport = z.infer<typeof reportSchema>;
export type GenerationResult = z.infer<typeof generationSchema>;
export type MaterialImage = z.infer<typeof materialSchema>;
export type EditOperation = { id: string; label: string; source: 'manual' | 'ai' | 'restore'; createdAt: string; before: ResumeData; after: ResumeData };
export type ResumeVersion = {
  id: string; title: string; role: string; updatedAt: string; accent: string; status: 'active' | 'draft' | 'archived';
  resume: ResumeData; messages: ChatMessage[]; past: ResumeData[]; future: ResumeData[]; history: EditOperation[];
  jobText: string; profileFileName: string; jobFileName: string; report: MatchReport | null; warnings: string[]; isDemo: boolean;
  profileText: string;
};
export type WorkspaceState = { schemaVersion: 2; versions: ResumeVersion[]; activeVersionId: string | null };
export type ModelMode = 'preset' | 'custom';
export type ModelConfig = { mode: ModelMode; presetId: string; url: string; apiKey: string; model: string; reasoningEffort?: ReasoningEffort };
export type ModelPreset = { id: string; label: string; provider: string; model: string; baseUrl: string; description: string; reasoningEffort?: ReasoningEffort };
